export const Products = [
  {
    id: 1,
    name: "Fjallraven - Foldsack No. 1 Backpac...",
    price: 1099,
    category: "Men's Clothing",
    img: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
  },
  {
    id: 2,
    name: "SanDisk SSD PLUS 1TB Internal SSD -...",
    price: 699,
    category: "Electronics",
    img: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
  },
  {
    id: 3,
    name: "Silicon Power 256GB SSD 3D NAND A55...",
    price: 5000,
    category: "Electronics",
    img: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
  },
  {
    id: 4,
    name: "WD 4TB Gaming Drive Works with Play...",
    price: 25000,
    category: "Electronics",
    img: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
  },
  {
    id: 5,
    name: "Acer SB220Q bi 21.5 inches Full HD ...",
    price: 19999,
    category: "Electronics",
    img: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
  },
  {
    id: 6,
    name: "Samsung 49-Inch CHG90 144Hz Curved ...",
    price: 70000,
    category: "Electronics",
    img: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
  },
  {
    id: 7,
    name: "BIYLACLESEN Women's 3-in-1 Snowboar...",
    price: 2599,
    category: "Women's Clothing",
    img: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
  },
  {
    id: 8,
    name: "Lock and Love Women's Removable Hoo...",
    price: 2599,
    category: "Women's Clothing",
    img: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
  },
  {
    id: 9,
    name: "Rain Jacket Women Windbreaker Strip...",
    price: 3333,
    category: "Women's Clothing",
    img: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
  },
  {
    id: 10,
    name: "MBJ Women's Solid Short Sleeve Boat...",
    price: 799,
    category: "Women's Clothing",
    img: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
  },
  {
    id: 11,
    name: "Opna Women's Short Sleeve Moisture...",
    price: 699,
    category: "Women's Clothing",
    img: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
  },
  {
    id: 12,
    name: "Mens Casual Premium Slim Fit T-Shir...",
    price: 300,
    category: "Men's Clothing",
    img: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
  },
  {
    id: 13,
    name: "DANVOUY Womens T Shirt Casual Cotto...",
    price: 999,
    category: "Women's Clothing",
    img: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
  },
  {
    id: 14,
    name: "Mens Cotton Jacket...",
    price: 1155,
    category: "Men's Clothing",
    img: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
  },
  {
    id: 15,
    name: "Mens Casual Slim Fit...",
    price: 900,
    category: "Men's Clothing",
    img: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
  },
  {
    id: 16,
    name: "John Hardy Women's Legends Naga Gol...",
    price: 6950,
    category: "Jewelry",
    img: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
  },
  {
    id: 17,
    name: "Solid Gold Petite Micropave ...",
    category: "Jewelry",
    price: 7500,
    img: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
  },
  {
    id: 18,
    name: "White Gold Plated Princess...",
    price: 3999,
    category: "Jewelry",
    img: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
  },
  {
    id: 19,
    name: "Pierced Owl Rose Gold Plated Stainl...",
    price: 10999,
    category: "Jewelry",
    img: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
  },
  {
    id: 20,
    name: "WD 2TB Elements Portable External H...",
    price: 80999,
    category: "Electronics",
    img: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
  },
];
